// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace LeaveManagement.Migrations
{
    [DbContext(typeof(EmplooyeesesContext))]
    partial class EmplooyeesesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Models.Emplooyeeses", b =>
                {
                    b.Property<int>("EID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EID");

                    b.ToTable("Emplooyeeses");
                });

            modelBuilder.Entity("Models.EmplooyeesesLeave", b =>
                {
                    b.Property<int>("LeaveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumOfDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("LeaveID");

                    b.ToTable("EmplooyeesesLeaves");
                });
#pragma warning restore 612, 618
        }
    }
}
